use std::collections::HashMap;

/// Template structure for output formatting
#[derive(Debug, Clone)]
pub struct Template {
    pub id: &'static str,
    pub name: &'static str,
    pub content: &'static str,
}

/// Default markdown template with full metadata
pub const DEFAULT_MARKDOWN_TEMPLATE: &str = r#"# Transcription: {filename}

**Date Processed:** {timestamp}
**Original File:** {source_file}
**Duration:** {duration}
**File Size:** {file_size_mb} MB
**Model:** {model_name}
**Processing Time:** {processing_time_s} seconds

---

## Transcription

{transcription_text}

---

*Generated by UltraWhisper - {workflow_name}*"#;

/// Simple markdown template with minimal formatting
pub const SIMPLE_MARKDOWN_TEMPLATE: &str = r#"# {filename}

{transcription_text}

---
*Transcribed on {timestamp}*"#;

/// Plain text template with no formatting
pub const PLAIN_TEXT_TEMPLATE: &str = "{transcription_text}";

/// Obsidian-optimized template with frontmatter
pub const OBSIDIAN_TEMPLATE: &str = r#"---
tags: [transcription, audio]
created: {timestamp}
source: {source_file}
model: {model_name}
duration: {duration}
---

# {filename}

{transcription_text}"#;

/// Get a template by ID
pub fn get_template(template_id: &str) -> &'static str {
    match template_id {
        "default_markdown" => DEFAULT_MARKDOWN_TEMPLATE,
        "simple_markdown" => SIMPLE_MARKDOWN_TEMPLATE,
        "plain_text" => PLAIN_TEXT_TEMPLATE,
        "obsidian" => OBSIDIAN_TEMPLATE,
        _ => DEFAULT_MARKDOWN_TEMPLATE,
    }
}

/// Get all available templates
pub fn get_available_templates() -> Vec<Template> {
    vec![
        Template {
            id: "default_markdown",
            name: "Default Markdown",
            content: DEFAULT_MARKDOWN_TEMPLATE,
        },
        Template {
            id: "simple_markdown",
            name: "Simple Markdown",
            content: SIMPLE_MARKDOWN_TEMPLATE,
        },
        Template {
            id: "plain_text",
            name: "Plain Text",
            content: PLAIN_TEXT_TEMPLATE,
        },
        Template {
            id: "obsidian",
            name: "Obsidian Note",
            content: OBSIDIAN_TEMPLATE,
        },
    ]
}

/// Apply a template with variable substitution
/// Simple token replacement - no conditionals or loops in v1
pub fn apply_template(template_id: &str, variables: &HashMap<&str, String>) -> String {
    let mut content = get_template(template_id).to_string();

    // Replace each variable in the template
    for (key, value) in variables {
        let placeholder = format!("{{{}}}", key);
        content = content.replace(&placeholder, value);
    }

    content
}

/// Helper to format timestamp in ISO-like format
pub fn format_timestamp(timestamp: u64) -> String {
    use chrono::{DateTime, Utc};

    let datetime = DateTime::<Utc>::from_timestamp(timestamp as i64, 0)
        .unwrap_or_else(|| DateTime::<Utc>::from_timestamp(0, 0).unwrap());
    datetime.format("%Y-%m-%d %H:%M:%S").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_substitution() {
        let mut vars = HashMap::new();
        vars.insert("filename", "test.wav".to_string());
        vars.insert("transcription_text", "Hello world".to_string());
        vars.insert("timestamp", "2025-10-25 10:00:00".to_string());

        let result = apply_template("simple_markdown", &vars);
        assert!(result.contains("# test.wav"));
        assert!(result.contains("Hello world"));
        assert!(result.contains("2025-10-25 10:00:00"));
    }

    #[test]
    fn test_get_template() {
        let template = get_template("default_markdown");
        assert!(template.contains("{filename}"));
        assert!(template.contains("{transcription_text}"));
    }
}