//! Template engine for output formatting
//!
//! ## Canonical Variables (Bundle 2+)
//!
//! The following variables are supported in all templates:
//!
//! - `{timestamp}` - Full ISO-like timestamp (YYYY-MM-DD HH:MM:SS)
//! - `{workflow_name}` - Name of the workflow that triggered this transcription
//! - `{model_name}` - Whisper model used (e.g., "whisper-small")
//! - `{duration}` - Recording duration formatted as "MM:SS" or "HH:MM:SS"
//! - `{transcription_text}` - The actual transcribed text
//!
//! ## Legacy Variables (Batch Processing)
//!
//! These are available for file-based batch processing:
//! - `{filename}` - Original filename
//! - `{source_file}` - Full path to source file
//! - `{file_size_mb}` - File size in MB
//! - `{processing_time_s}` - Processing time in seconds
//!
//! ## Planned Future Variables
//!
//! - `{date}` - Date only (YYYY-MM-DD)
//! - `{time}` - Time only (HH:MM:SS)
//! - `{audio_path}` - Path to saved audio file
//! - `{trigger_type}` - How the workflow was triggered (hotkey, folder_watch, etc.)

use std::collections::HashMap;

/// Template structure for output formatting
#[derive(Debug, Clone)]
pub struct Template {
    pub id: &'static str,
    pub name: &'static str,
    pub content: &'static str,
}

/// Default markdown template with full metadata
pub const DEFAULT_MARKDOWN_TEMPLATE: &str = r#"# Transcription: {filename}

**Date Processed:** {timestamp}
**Original File:** {source_file}
**Duration:** {duration}
**File Size:** {file_size_mb} MB
**Model:** {model_name}
**Processing Time:** {processing_time_s} seconds

---

## Transcription

{transcription_text}

---

*Generated by UltraWhisper - {workflow_name}*"#;

/// Simple markdown template with minimal formatting
pub const SIMPLE_MARKDOWN_TEMPLATE: &str = r#"# {filename}

{transcription_text}

---
*Transcribed on {timestamp}*"#;

/// Plain text template with no formatting
pub const PLAIN_TEXT_TEMPLATE: &str = "{transcription_text}";

/// Obsidian-optimized template with frontmatter
pub const OBSIDIAN_TEMPLATE: &str = r#"---
tags: [transcription, audio]
created: {timestamp}
source: {source_file}
model: {model_name}
duration: {duration}
---

# {filename}

{transcription_text}"#;

/// Get a template by ID
pub fn get_template(template_id: &str) -> &'static str {
    match template_id {
        "default_markdown" => DEFAULT_MARKDOWN_TEMPLATE,
        "simple_markdown" => SIMPLE_MARKDOWN_TEMPLATE,
        "plain_text" => PLAIN_TEXT_TEMPLATE,
        "obsidian" => OBSIDIAN_TEMPLATE,
        _ => DEFAULT_MARKDOWN_TEMPLATE,
    }
}

/// Get all available templates
pub fn get_available_templates() -> Vec<Template> {
    vec![
        Template {
            id: "default_markdown",
            name: "Default Markdown",
            content: DEFAULT_MARKDOWN_TEMPLATE,
        },
        Template {
            id: "simple_markdown",
            name: "Simple Markdown",
            content: SIMPLE_MARKDOWN_TEMPLATE,
        },
        Template {
            id: "plain_text",
            name: "Plain Text",
            content: PLAIN_TEXT_TEMPLATE,
        },
        Template {
            id: "obsidian",
            name: "Obsidian Note",
            content: OBSIDIAN_TEMPLATE,
        },
    ]
}

/// Apply a template with variable substitution
/// Simple token replacement - no conditionals or loops in v1
pub fn apply_template(template_id: &str, variables: &HashMap<&str, String>) -> String {
    let mut content = get_template(template_id).to_string();

    // Replace each variable in the template
    for (key, value) in variables {
        let placeholder = format!("{{{}}}", key);
        content = content.replace(&placeholder, value);
    }

    content
}

/// Helper to format timestamp in ISO-like format
pub fn format_timestamp(timestamp: u64) -> String {
    use chrono::{DateTime, Utc};

    let datetime = DateTime::<Utc>::from_timestamp(timestamp as i64, 0)
        .unwrap_or_else(|| DateTime::<Utc>::from_timestamp(0, 0).unwrap());
    datetime.format("%Y-%m-%d %H:%M:%S").to_string()
}

/// Helper to format duration in milliseconds as HH:MM:SS or MM:SS
pub fn format_duration(duration_ms: u64) -> String {
    let total_seconds = duration_ms / 1000;
    let hours = total_seconds / 3600;
    let minutes = (total_seconds % 3600) / 60;
    let seconds = total_seconds % 60;

    if hours > 0 {
        format!("{:02}:{:02}:{:02}", hours, minutes, seconds)
    } else {
        format!("{:02}:{:02}", minutes, seconds)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_substitution() {
        let mut vars = HashMap::new();
        vars.insert("filename", "test.wav".to_string());
        vars.insert("transcription_text", "Hello world".to_string());
        vars.insert("timestamp", "2025-10-25 10:00:00".to_string());

        let result = apply_template("simple_markdown", &vars);
        assert!(result.contains("# test.wav"));
        assert!(result.contains("Hello world"));
        assert!(result.contains("2025-10-25 10:00:00"));
    }

    #[test]
    fn test_get_template() {
        let template = get_template("default_markdown");
        assert!(template.contains("{filename}"));
        assert!(template.contains("{transcription_text}"));
    }

    #[test]
    fn test_format_duration() {
        // Test short duration (under 1 minute)
        assert_eq!(format_duration(30_000), "00:30");

        // Test medium duration (minutes and seconds)
        assert_eq!(format_duration(125_000), "02:05");

        // Test long duration (hours, minutes, seconds)
        assert_eq!(format_duration(3_665_000), "01:01:05");

        // Test zero duration
        assert_eq!(format_duration(0), "00:00");
    }

    #[test]
    fn test_canonical_variables() {
        // Test that canonical variables work in templates
        let mut vars = HashMap::new();
        vars.insert("timestamp", "2025-10-29 10:00:00".to_string());
        vars.insert("workflow_name", "Quick Capture".to_string());
        vars.insert("model_name", "whisper-small".to_string());
        vars.insert("duration", "02:30".to_string());
        vars.insert("transcription_text", "Test transcription".to_string());

        let template = "{workflow_name} at {timestamp}\nDuration: {duration}\nModel: {model_name}\n\n{transcription_text}";
        let mut content = template.to_string();

        for (key, value) in &vars {
            let placeholder = format!("{{{}}}", key);
            content = content.replace(&placeholder, value);
        }

        assert!(content.contains("Quick Capture"));
        assert!(content.contains("2025-10-29 10:00:00"));
        assert!(content.contains("02:30"));
        assert!(content.contains("whisper-small"));
        assert!(content.contains("Test transcription"));
    }
}